spring:
  profiles:
    active: testlocal

  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB

security:
  oauth2:
    client:
      client-id: webgui
      client-secret: ovarkills11
      user-authorization-uri: http://34.102.169.103/uaa/oauth/authorize
      access-token-uri:  http://34.102.169.103/uaa/oauth/token
    resource:
      token-info-uri: http://34.102.169.103/uaa/oauth/check_token

server:
  servlet:
    session:
      cookie:
        name: DFB_SESSION2
  port: 8080

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
        timeout:
          enabled: false

dbURI: http://34.102.169.103
statsURI: http://34.102.169.103
authURI: http://34.102.169.103