spring:
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB

security:
  oauth2:
    client:
      client-id: webgui
      client-secret: demopass1234
      user-authorization-uri: http://localhost:9191/uaa/oauth/authorize
      access-token-uri:  http://localhost:9191/uaa/oauth/token
    resource:
      token-info-uri: http://localhost:9191/uaa/oauth/check_token

server:
  servlet:
    session:
      cookie:
        name: DFB_SESSION2
  port: 8080

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
        timeout:
          enabled: false

dbURI: http://localhost:8081
statsURI: http://localhost:8100
authURI: http://localhost:9191

#logging:
#  level:
#    root: debug